ENV_DATABASE_PREFIX: DEMO_
ENV_WAREHOUSE_PREFIX: DEMO_
ENV_ROLE_PREFIX: DEMO_
ENV_PROCEDURE_PREFIX: DEMO_
ENV_FUNCTION_PREFIX: DEMO_
OBJECT_METADATA_ONLY: True
MAX_THREADS: 15
HANDLE_OWNERSHIP: GRANT
DEPLOY_ENV: demo
IMPORT_DATABASES:
- ANALYTICS
- CONTROL
- RAW
- SECURITY
IMPORT_OBJECT_TYPES:
- DATABASE
- SCHEMA
- OBJECT
- PROCEDURE
CLASSIFY_DATABASES:
- ANALYTICS
CLASSIFY_TAGS_DB_SCHEMA: CONTROL.GOVERNANCE
CLASSIFY_IGNORE_TAGS:
VARS:
- my_comment: some demo comment
- another_var: some other var in demo
- env: demo